package entities;
// Generated 29 oct. 2014 23:39:21 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customers implements java.io.Serializable {

	private BigDecimal custId;
	private String custFirstName;
	private String custLastName;
	private char custGender;
	private short custYearOfBirth;
	private String custMaritalStatus;
	private String custStreetAddress;
	private String custPostalCode;
	private String custCity;
	private BigDecimal custCityId;
	private String custStateProvince;
	private BigDecimal custStateProvinceId;
	private String custMainPhoneNumber;
	private String custIncomeLevel;
	private BigDecimal custCreditLimit;
	private String custEmail;
	private String custTotal;
	private BigDecimal custTotalId;
	private BigDecimal custSrcId;
	private Date custEffFrom;
	private Date custEffTo;
	private String custValid;
	private Set saleses = new HashSet(0);

	public Customers() {
	}

	public Customers(BigDecimal custId,
			String custFirstName, String custLastName, char custGender,
			short custYearOfBirth, String custStreetAddress,
			String custPostalCode, String custCity, BigDecimal custCityId,
			String custStateProvince, BigDecimal custStateProvinceId,
			String custMainPhoneNumber, String custTotal, BigDecimal custTotalId) {
		this.custId = custId;
		this.custFirstName = custFirstName;
		this.custLastName = custLastName;
		this.custGender = custGender;
		this.custYearOfBirth = custYearOfBirth;
		this.custStreetAddress = custStreetAddress;
		this.custPostalCode = custPostalCode;
		this.custCity = custCity;
		this.custCityId = custCityId;
		this.custStateProvince = custStateProvince;
		this.custStateProvinceId = custStateProvinceId;
		this.custMainPhoneNumber = custMainPhoneNumber;
		this.custTotal = custTotal;
		this.custTotalId = custTotalId;
	}

	public Customers(BigDecimal custId,
			String custFirstName, String custLastName, char custGender,
			short custYearOfBirth, String custMaritalStatus,
			String custStreetAddress, String custPostalCode, String custCity,
			BigDecimal custCityId, String custStateProvince,
			BigDecimal custStateProvinceId, String custMainPhoneNumber,
			String custIncomeLevel, BigDecimal custCreditLimit,
			String custEmail, String custTotal, BigDecimal custTotalId,
			BigDecimal custSrcId, Date custEffFrom, Date custEffTo,
			String custValid, Set saleses) {
		this.custId = custId;
		this.custFirstName = custFirstName;
		this.custLastName = custLastName;
		this.custGender = custGender;
		this.custYearOfBirth = custYearOfBirth;
		this.custMaritalStatus = custMaritalStatus;
		this.custStreetAddress = custStreetAddress;
		this.custPostalCode = custPostalCode;
		this.custCity = custCity;
		this.custCityId = custCityId;
		this.custStateProvince = custStateProvince;
		this.custStateProvinceId = custStateProvinceId;
		this.custMainPhoneNumber = custMainPhoneNumber;
		this.custIncomeLevel = custIncomeLevel;
		this.custCreditLimit = custCreditLimit;
		this.custEmail = custEmail;
		this.custTotal = custTotal;
		this.custTotalId = custTotalId;
		this.custSrcId = custSrcId;
		this.custEffFrom = custEffFrom;
		this.custEffTo = custEffTo;
		this.custValid = custValid;
		this.saleses = saleses;
	}

	public BigDecimal getCustId() {
		return this.custId;
	}

	public void setCustId(BigDecimal custId) {
		this.custId = custId;
	}

	public String getCustFirstName() {
		return this.custFirstName;
	}

	public void setCustFirstName(String custFirstName) {
		this.custFirstName = custFirstName;
	}

	public String getCustLastName() {
		return this.custLastName;
	}

	public void setCustLastName(String custLastName) {
		this.custLastName = custLastName;
	}

	public char getCustGender() {
		return this.custGender;
	}

	public void setCustGender(char custGender) {
		this.custGender = custGender;
	}

	public short getCustYearOfBirth() {
		return this.custYearOfBirth;
	}

	public void setCustYearOfBirth(short custYearOfBirth) {
		this.custYearOfBirth = custYearOfBirth;
	}

	public String getCustMaritalStatus() {
		return this.custMaritalStatus;
	}

	public void setCustMaritalStatus(String custMaritalStatus) {
		this.custMaritalStatus = custMaritalStatus;
	}

	public String getCustStreetAddress() {
		return this.custStreetAddress;
	}

	public void setCustStreetAddress(String custStreetAddress) {
		this.custStreetAddress = custStreetAddress;
	}

	public String getCustPostalCode() {
		return this.custPostalCode;
	}

	public void setCustPostalCode(String custPostalCode) {
		this.custPostalCode = custPostalCode;
	}

	public String getCustCity() {
		return this.custCity;
	}

	public void setCustCity(String custCity) {
		this.custCity = custCity;
	}

	public BigDecimal getCustCityId() {
		return this.custCityId;
	}

	public void setCustCityId(BigDecimal custCityId) {
		this.custCityId = custCityId;
	}

	public String getCustStateProvince() {
		return this.custStateProvince;
	}

	public void setCustStateProvince(String custStateProvince) {
		this.custStateProvince = custStateProvince;
	}

	public BigDecimal getCustStateProvinceId() {
		return this.custStateProvinceId;
	}

	public void setCustStateProvinceId(BigDecimal custStateProvinceId) {
		this.custStateProvinceId = custStateProvinceId;
	}

	public String getCustMainPhoneNumber() {
		return this.custMainPhoneNumber;
	}

	public void setCustMainPhoneNumber(String custMainPhoneNumber) {
		this.custMainPhoneNumber = custMainPhoneNumber;
	}

	public String getCustIncomeLevel() {
		return this.custIncomeLevel;
	}

	public void setCustIncomeLevel(String custIncomeLevel) {
		this.custIncomeLevel = custIncomeLevel;
	}

	public BigDecimal getCustCreditLimit() {
		return this.custCreditLimit;
	}

	public void setCustCreditLimit(BigDecimal custCreditLimit) {
		this.custCreditLimit = custCreditLimit;
	}

	public String getCustEmail() {
		return this.custEmail;
	}

	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}

	public String getCustTotal() {
		return this.custTotal;
	}

	public void setCustTotal(String custTotal) {
		this.custTotal = custTotal;
	}

	public BigDecimal getCustTotalId() {
		return this.custTotalId;
	}

	public void setCustTotalId(BigDecimal custTotalId) {
		this.custTotalId = custTotalId;
	}

	public BigDecimal getCustSrcId() {
		return this.custSrcId;
	}

	public void setCustSrcId(BigDecimal custSrcId) {
		this.custSrcId = custSrcId;
	}

	public Date getCustEffFrom() {
		return this.custEffFrom;
	}

	public void setCustEffFrom(Date custEffFrom) {
		this.custEffFrom = custEffFrom;
	}

	public Date getCustEffTo() {
		return this.custEffTo;
	}

	public void setCustEffTo(Date custEffTo) {
		this.custEffTo = custEffTo;
	}

	public String getCustValid() {
		return this.custValid;
	}

	public void setCustValid(String custValid) {
		this.custValid = custValid;
	}

	public Set getSaleses() {
		return this.saleses;
	}

	public void setSaleses(Set saleses) {
		this.saleses = saleses;
	}

}
