package entities;
// Generated 29 oct. 2014 23:39:21 by Hibernate Tools 3.4.0.CR1

/**
 * Sales generated by hbm2java
 */
public class Sales implements java.io.Serializable {

	private SalesId id;
	private Customers customers;

	public Sales() {
	}

	public Sales(SalesId id, Customers customers) {
		this.id = id;
		this.customers = customers;
	}

	public SalesId getId() {
		return this.id;
	}

	public void setId(SalesId id) {
		this.id = id;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

}
