package entities;
// Generated 29 oct. 2014 23:39:21 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SalesId generated by hbm2java
 */
public class SalesId implements java.io.Serializable {

	private BigDecimal prodId;
	private BigDecimal custId;
	private Date timeId;
	private BigDecimal channelId;
	private BigDecimal promoId;
	private BigDecimal quantitySold;
	private BigDecimal amountSold;

	public SalesId() {
	}

	public SalesId(BigDecimal prodId, BigDecimal custId, Date timeId,
			BigDecimal channelId, BigDecimal promoId, BigDecimal quantitySold,
			BigDecimal amountSold) {
		this.prodId = prodId;
		this.custId = custId;
		this.timeId = timeId;
		this.channelId = channelId;
		this.promoId = promoId;
		this.quantitySold = quantitySold;
		this.amountSold = amountSold;
	}

	public BigDecimal getProdId() {
		return this.prodId;
	}

	public void setProdId(BigDecimal prodId) {
		this.prodId = prodId;
	}

	public BigDecimal getCustId() {
		return this.custId;
	}

	public void setCustId(BigDecimal custId) {
		this.custId = custId;
	}

	public Date getTimeId() {
		return this.timeId;
	}

	public void setTimeId(Date timeId) {
		this.timeId = timeId;
	}

	public BigDecimal getChannelId() {
		return this.channelId;
	}

	public void setChannelId(BigDecimal channelId) {
		this.channelId = channelId;
	}

	public BigDecimal getPromoId() {
		return this.promoId;
	}

	public void setPromoId(BigDecimal promoId) {
		this.promoId = promoId;
	}

	public BigDecimal getQuantitySold() {
		return this.quantitySold;
	}

	public void setQuantitySold(BigDecimal quantitySold) {
		this.quantitySold = quantitySold;
	}

	public BigDecimal getAmountSold() {
		return this.amountSold;
	}

	public void setAmountSold(BigDecimal amountSold) {
		this.amountSold = amountSold;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalesId))
			return false;
		SalesId castOther = (SalesId) other;

		return ((this.getProdId() == castOther.getProdId()) || (this
				.getProdId() != null && castOther.getProdId() != null && this
				.getProdId().equals(castOther.getProdId())))
				&& ((this.getCustId() == castOther.getCustId()) || (this
						.getCustId() != null && castOther.getCustId() != null && this
						.getCustId().equals(castOther.getCustId())))
				&& ((this.getTimeId() == castOther.getTimeId()) || (this
						.getTimeId() != null && castOther.getTimeId() != null && this
						.getTimeId().equals(castOther.getTimeId())))
				&& ((this.getChannelId() == castOther.getChannelId()) || (this
						.getChannelId() != null
						&& castOther.getChannelId() != null && this
						.getChannelId().equals(castOther.getChannelId())))
				&& ((this.getPromoId() == castOther.getPromoId()) || (this
						.getPromoId() != null && castOther.getPromoId() != null && this
						.getPromoId().equals(castOther.getPromoId())))
				&& ((this.getQuantitySold() == castOther.getQuantitySold()) || (this
						.getQuantitySold() != null
						&& castOther.getQuantitySold() != null && this
						.getQuantitySold().equals(castOther.getQuantitySold())))
				&& ((this.getAmountSold() == castOther.getAmountSold()) || (this
						.getAmountSold() != null
						&& castOther.getAmountSold() != null && this
						.getAmountSold().equals(castOther.getAmountSold())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProdId() == null ? 0 : this.getProdId().hashCode());
		result = 37 * result
				+ (getCustId() == null ? 0 : this.getCustId().hashCode());
		result = 37 * result
				+ (getTimeId() == null ? 0 : this.getTimeId().hashCode());
		result = 37 * result
				+ (getChannelId() == null ? 0 : this.getChannelId().hashCode());
		result = 37 * result
				+ (getPromoId() == null ? 0 : this.getPromoId().hashCode());
		result = 37
				* result
				+ (getQuantitySold() == null ? 0 : this.getQuantitySold()
						.hashCode());
		result = 37
				* result
				+ (getAmountSold() == null ? 0 : this.getAmountSold()
						.hashCode());
		return result;
	}

}
